development:
  adapter: mysql2
  encoding: utf8
  database: OccupationalHealth
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: OccupationalHealth_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: OccupationalHealth
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
